name: portfolio
description: personal developer portfolio
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.10.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  functional_widget: ^0.10.1
  build_runner: ^2.3.3
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - images/kotlin.svg
    - images/flutter.svg
    - images/dart.svg
    - images/firebase.svg
    - images/jira.svg
    - images/admob.svg
    - images/typescript.svg
    - images/java.svg
    - images/google_play_badge.png
    - images/app_store_badge.svg
    - images/jetpack_compose.png
    - images/riverpod.svg
    - images/algolia.svg
    - images/realm.svg

flutter_gen:
  integrations:
    flutter_svg: true