name: portfolio
description: personal developer portfolio
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  functional_widget_annotation: ^0.10.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  functional_widget: ^0.10.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_gen_runner:
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/kotlin.svg
    - images/flutter.svg
    - images/dart.svg
    - images/firebase.png
    - images/jira.png
    - images/admob.svg
    - images/typescript.svg
    - images/java.svg
    - images/google_play_badge.png
    - images/app_store_badge.svg
    - images/jetpack_compose.png
    - images/riverpod.svg
    - images/algolia.svg
    - images/realm.png
    - images/figma.svg
    - images/node_js.svg
    - images/radiko_cover.png
    - images/train_cover.png
    - images/itsumuso_cover.webp
    - images/qiita.png
    - images/github.svg

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "launcher.png"
    theme_color: "#FF9800"